#usuarioAdmin=admin
#passwordAdmin=admin
paises=ficheros/paises.xml
#credenciales=ficheros/credenciales.txt
#espectaculos=ficheros/espectaculos.dat
#url=jdbc:mysql://localhost:3306/circodb
#dbuser=root
#dbpass=
#
##no usar CREATE, que destruye las tablas y las crea
#spring.jpa.hibernate.ddl-auto=validate

##para ver que hace spring por debajo
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/circodb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#update crea si no existe // create borra-y-crea cada vez
spring.jpa.hibernate.ddl-auto=update

	
#para PRUEBAS (ver consultas en consola)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

usuarioAdmin=admin
passwordAdmin=admin

